### ISSUE TITLE
Can't fire cannons in Firefox

### ISSUE THREAD

**Issue by rpaladin** [BabylonJS/SpacePirates#2]
Left mouse button to fire cannons don't work in Firefox:
* Using latest Firefox (v100.0)
* No browser console errors are raised
* Other inputs such as movement seem to work fine
* Browser window is confirmed active
* Game is confirmed unpaused
* All three game-modes (solo, squad, battle) fail to fire cannons

<hr />

Firing of cannons work **fine** in Microsoft Edge however.

**Comment by CedricGuillemet** [comment]
I'm taking a look.

**Comment by CedricGuillemet** [comment]
@PolygonalSun there is no mouse down event catched here : https://github.com/BabylonJS/SpacePirates/blob/9e6aa1b5fcf8b436a242624d702d9e9e3d9893e0/app_package/src/Playground/Inputs/Input.ts#L125
Any idea why it happens?

**Comment by PolygonalSun** [comment]
> @PolygonalSun there is no mouse down event catched here :
> 
> https://github.com/BabylonJS/SpacePirates/blob/9e6aa1b5fcf8b436a242624d702d9e9e3d9893e0/app_package/src/Playground/Inputs/Input.ts#L125
> 
> 
> Any idea why it happens?

For some reason, Firefox wasn't firing `mousedown` events properly so I changed a bit of the logic to use `pointerdown` instead.  Additionally, I've added a conditional statement to use `mousedown` for Safari as it has issues with `pointerdown`.

**Comment by rpaladin** [comment]
I can fire cannons now in Firefox! However, both in Firefox/MS Edge.

However, I still cannot fire missiles. Is there some, pickup that the character is required to collect in order to fire them?

**Comment by CedricGuillemet** [comment]
reticle need to be red (ship is tracked) before you can fire a missile.

**Comment by darraghjburke** [comment]
Closing since this issue seems to be resolved. Let us know if you have any more trouble with Firefox!
